services:
  sql:
    container_name: "mysql-exe-js"
    image: mysql:9
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3305:3306"

volumes:
  mysql_data:
